name: Electron Build & Release

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, ubuntu-24.04-arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run make:mac

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run make:win

      - name: Build for Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-24.04-arm64" ]]; then
            npm run make:linux-arm64
          else
            npm run make:linux-x64
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinkerpad-builds-${{ matrix.os }}
          path: out/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tinkerpad-builds-macos-latest/out/**/*.zip
            tinkerpad-builds-macos-latest/out/**/*.dmg
            tinkerpad-builds-windows-latest/out/**/*.exe
            tinkerpad-builds-windows-latest/out/**/*.nupkg
            tinkerpad-builds-ubuntu-latest/out/**/*.deb
            tinkerpad-builds-ubuntu-latest/out/**/*.rpm
            tinkerpad-builds-ubuntu-latest/out/**/*.AppImage
            tinkerpad-builds-ubuntu-24.04-arm64/out/**/*.deb
            tinkerpad-builds-ubuntu-24.04-arm64/out/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}