#name: Electron Build & Release
#
#on:
#  push:
#    branches:
#      - main
#      - release/*
#    tags:
#      - 'v*'
#
#jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
#        os: [macos-latest, windows-latest, ubuntu-latest]
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#
#      - name: Install Dependencies
#        run: npm ci
#
#      - name: Build for macOS
#        if: matrix.os == 'macos-latest'
#        run: npm run make:mac
#
#      - name: Build for Windows
#        if: matrix.os == 'windows-latest'
#        run: npm run make:win
#
#      - name: Build for Linux
#        if: matrix.os == 'ubuntu-latest'
#        run: npm run make:linux
#
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: tinkerpad-builds-${{ matrix.os }}
#          path: out/
#
#  release:
#    runs-on: ubuntu-latest
#    needs: build
#    if: startsWith(github.ref, 'refs/tags/v')
#
#    steps:
#      - name: Download all build artifacts
#        uses: actions/download-artifact@v4
#
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            tinkerpad-builds-macos-latest/out/**/*.zip
#            tinkerpad-builds-macos-latest/out/**/*.dmg
#            tinkerpad-builds-windows-latest/out/**/*.exe
#            tinkerpad-builds-windows-latest/out/**/*.nupkg
#            tinkerpad-builds-ubuntu-latest/out/**/*.deb
#            tinkerpad-builds-ubuntu-latest/out/**/*.rpm
#            tinkerpad-builds-ubuntu-latest/out/**/*.AppImage
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Electron Build & Release

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # macOS builds
          - os: macos-latest
            platform: darwin
            arch: x64
            script: make:mac
          - os: macos-latest
            platform: darwin
            arch: arm64
            script: make:mac-arm
          # Windows builds
          - os: windows-latest
            platform: win32
            arch: x64
            script: make:win
          - os: windows-latest
            platform: win32
            arch: arm64
            script: make:win-arm
          # Linux builds
          - os: ubuntu-latest
            platform: linux
            arch: x64
            script: make:linux
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            script: make:linux-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run ${{ matrix.script }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinkerpad-${{ matrix.platform }}-${{ matrix.arch }}
          path: out/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tinkerpad-*/out/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}