name: Release and Build Electron App

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # only macOS + Windows for now
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Make distributable
        run: npm run make

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}